//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectorWeb.Reports {
    
    public partial class Docs_Conclusion_Examination : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "InspectorWeb.Reports.Docs_Conclusion_Examination.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.Text17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text17");
            this.Text4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text4");
            this.Text5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text5");
            this.Text6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text6");
            this.Text7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text7");
            this.Text1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text1");

            // Parameters
            this.doc_id = reportInitializer.GetParameter("doc_id");
            this.doc_date = reportInitializer.GetParameter("doc_date");
            this.specialist1 = reportInitializer.GetParameter("specialist1");
            this.exams = reportInitializer.GetParameter("exams");
            this.doc_num = reportInitializer.GetParameter("doc_num");
            this.director_div_karantin = reportInitializer.GetParameter("director_div_karantin");
            this.org_title = reportInitializer.GetParameter("org_title");
            this.org_adress = reportInitializer.GetParameter("org_adress");

            // Calculated Fields
            this.is_fact_address = reportInitializer.GetCalculatedField("is_fact_address");
            this.is_sert = reportInitializer.GetCalculatedField("is_sert");
            this.is_transport = reportInitializer.GetCalculatedField("is_transport");
            this.is_bill = reportInitializer.GetCalculatedField("is_bill");
            this.is_parent_document = reportInitializer.GetCalculatedField("is_parent_document");
            this.is_samples = reportInitializer.GetCalculatedField("is_samples");
            this.isMark = reportInitializer.GetCalculatedField("isMark");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.XRLabel Text17;
        private DevExpress.XtraReports.UI.XRLabel Text4;
        private DevExpress.XtraReports.UI.XRLabel Text5;
        private DevExpress.XtraReports.UI.XRLabel Text6;
        private DevExpress.XtraReports.UI.XRLabel Text7;
        private DevExpress.XtraReports.UI.XRLabel Text1;
        private DevExpress.XtraReports.UI.CalculatedField is_fact_address;
        private DevExpress.XtraReports.UI.CalculatedField is_sert;
        private DevExpress.XtraReports.UI.CalculatedField is_transport;
        private DevExpress.XtraReports.UI.CalculatedField is_bill;
        private DevExpress.XtraReports.UI.CalculatedField is_parent_document;
        private DevExpress.XtraReports.UI.CalculatedField is_samples;
        private DevExpress.XtraReports.UI.CalculatedField isMark;
        private DevExpress.XtraReports.Parameters.Parameter doc_id;
        private DevExpress.XtraReports.Parameters.Parameter doc_date;
        private DevExpress.XtraReports.Parameters.Parameter specialist1;
        private DevExpress.XtraReports.Parameters.Parameter exams;
        private DevExpress.XtraReports.Parameters.Parameter doc_num;
        private DevExpress.XtraReports.Parameters.Parameter director_div_karantin;
        private DevExpress.XtraReports.Parameters.Parameter org_title;
        private DevExpress.XtraReports.Parameters.Parameter org_adress;
    }
}
