//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectorWeb.Reports {
    
    public partial class Docs_Bills_Post_add : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "InspectorWeb.Reports.Docs_Bills_Post_add.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.Line17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line17");
            this.RecordNumber1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("RecordNumber1");
            this.unit1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("unit1");
            this.count1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("count1");
            this.sum1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("sum1");
            this.Text11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text11");
            this.fullrate1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("fullrate1");
            this.Text1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text1");
            this.Line1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line1");
            this.Text19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text19");
            this.Text3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text3");
            this.Text4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text4");
            this.Text6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text6");
            this.Text2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text2");
            this.Text5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text5");
            this.Text21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text21");
            this.Text7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text7");
            this.Text8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text8");
            this.Text9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text9");
            this.Text10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text10");
            this.Box2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandBox>("Box2");
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");

            // Parameters
            this.sum_without_nds = reportInitializer.GetParameter("sum_without_nds");
            this.bill_number = reportInitializer.GetParameter("bill_number");
            this.doc_date = reportInitializer.GetParameter("doc_date");
            this.org_director = reportInitializer.GetParameter("org_director");
            this.org_buch = reportInitializer.GetParameter("org_buch");
            this.org_title = reportInitializer.GetParameter("org_title");
            this.org_adress = reportInitializer.GetParameter("org_adress");
            this.string_sum = reportInitializer.GetParameter("string_sum");
            this.string_sum_nds = reportInitializer.GetParameter("string_sum_nds");
            this.line_number = reportInitializer.GetParameter("line_number");

            // Calculated Fields
            this.sum_nds = reportInitializer.GetCalculatedField("sum_nds");
            this.full_rate = reportInitializer.GetCalculatedField("full_rate");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.XRLine Line17;
        private DevExpress.XtraReports.UI.XRLabel RecordNumber1;
        private DevExpress.XtraReports.UI.XRLabel unit1;
        private DevExpress.XtraReports.UI.XRLabel count1;
        private DevExpress.XtraReports.UI.XRLabel sum1;
        private DevExpress.XtraReports.UI.XRLabel Text11;
        private DevExpress.XtraReports.UI.XRLabel fullrate1;
        private DevExpress.XtraReports.UI.XRLabel Text1;
        private DevExpress.XtraReports.UI.XRLine Line1;
        private DevExpress.XtraReports.UI.XRLabel Text19;
        private DevExpress.XtraReports.UI.XRLabel Text3;
        private DevExpress.XtraReports.UI.XRLabel Text4;
        private DevExpress.XtraReports.UI.XRLabel Text6;
        private DevExpress.XtraReports.UI.XRLabel Text2;
        private DevExpress.XtraReports.UI.XRLabel Text5;
        private DevExpress.XtraReports.UI.XRLabel Text21;
        private DevExpress.XtraReports.UI.XRLabel Text7;
        private DevExpress.XtraReports.UI.XRLabel Text8;
        private DevExpress.XtraReports.UI.XRLabel Text9;
        private DevExpress.XtraReports.UI.XRLabel Text10;
        private DevExpress.XtraReports.UI.XRCrossBandBox Box2;
        private DevExpress.XtraReports.UI.CalculatedField sum_nds;
        private DevExpress.XtraReports.UI.CalculatedField full_rate;
        private DevExpress.XtraReports.Parameters.Parameter sum_without_nds;
        private DevExpress.XtraReports.Parameters.Parameter bill_number;
        private DevExpress.XtraReports.Parameters.Parameter doc_date;
        private DevExpress.XtraReports.Parameters.Parameter org_director;
        private DevExpress.XtraReports.Parameters.Parameter org_buch;
        private DevExpress.XtraReports.Parameters.Parameter org_title;
        private DevExpress.XtraReports.Parameters.Parameter org_adress;
        private DevExpress.XtraReports.Parameters.Parameter string_sum;
        private DevExpress.XtraReports.Parameters.Parameter string_sum_nds;
        private DevExpress.XtraReports.Parameters.Parameter line_number;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
    }
}
