//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectorWeb.Reports {
    
    public partial class Docs_Bills_Pre_add : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "InspectorWeb.Reports.Docs_Bills_Pre_add.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.RecordNumber1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("RecordNumber1");
            this.unit2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("unit2");
            this.count1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("count1");
            this.sum1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("sum1");
            this.Line17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line17");
            this.sumnds1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("sumnds1");
            this.sumend1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("sumend1");
            this.Text1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text1");
            this.fullrate1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("fullrate1");
            this.Text7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text7");
            this.Text14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text14");
            this.Text13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text13");
            this.Text12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text12");
            this.Text2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text2");
            this.Text10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text10");
            this.Text9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text9");
            this.Text8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text8");
            this.Text3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text3");
            this.Section4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("Section4");
            this.ReportFooterSection2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("ReportFooterSection2");
            this.Sumofsumnds1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Sumofsumnds1");
            this.Text15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text15");
            this.Text16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text16");
            this.docsum1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("docsum1");
            this.Text4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text4");
            this.Box2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandBox>("Box2");
            this.Line12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line12");
            this.Line11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line11");
            this.Line10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line10");
            this.Line9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line9");
            this.Line8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line8");
            this.Line15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line15");
            this.Line18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line18");
            this.Box3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandBox>("Box3");
            this.Box4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandBox>("Box4");

            // Parameters
            this.org_title = reportInitializer.GetParameter("org_title");
            this.org_director = reportInitializer.GetParameter("org_director");
            this.doc_number = reportInitializer.GetParameter("doc_number");
            this.agreement_note = reportInitializer.GetParameter("agreement_note");
            this.string_sum = reportInitializer.GetParameter("string_sum");
            this.line_number = reportInitializer.GetParameter("line_number");

            // Calculated Fields
            this.sum_nds = reportInitializer.GetCalculatedField("sum_nds");
            this.sum_end = reportInitializer.GetCalculatedField("sum_end");
            this.full_rate = reportInitializer.GetCalculatedField("full_rate");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.XRLabel RecordNumber1;
        private DevExpress.XtraReports.UI.XRLabel unit2;
        private DevExpress.XtraReports.UI.XRLabel count1;
        private DevExpress.XtraReports.UI.XRLabel sum1;
        private DevExpress.XtraReports.UI.XRLine Line17;
        private DevExpress.XtraReports.UI.XRLabel sumnds1;
        private DevExpress.XtraReports.UI.XRLabel sumend1;
        private DevExpress.XtraReports.UI.XRLabel Text1;
        private DevExpress.XtraReports.UI.XRLabel fullrate1;
        private DevExpress.XtraReports.UI.XRLabel Text7;
        private DevExpress.XtraReports.UI.XRLabel Text14;
        private DevExpress.XtraReports.UI.XRLabel Text13;
        private DevExpress.XtraReports.UI.XRLabel Text12;
        private DevExpress.XtraReports.UI.XRLabel Text2;
        private DevExpress.XtraReports.UI.XRLabel Text10;
        private DevExpress.XtraReports.UI.XRLabel Text9;
        private DevExpress.XtraReports.UI.XRLabel Text8;
        private DevExpress.XtraReports.UI.XRLabel Text3;
        private DevExpress.XtraReports.UI.SubBand Section4;
        private DevExpress.XtraReports.UI.SubBand ReportFooterSection2;
        private DevExpress.XtraReports.UI.XRLabel Sumofsumnds1;
        private DevExpress.XtraReports.UI.XRLabel Text15;
        private DevExpress.XtraReports.UI.XRLabel Text16;
        private DevExpress.XtraReports.UI.XRLabel docsum1;
        private DevExpress.XtraReports.UI.XRLabel Text4;
        private DevExpress.XtraReports.UI.XRCrossBandBox Box2;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line12;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line11;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line10;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line9;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line8;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line15;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line18;
        private DevExpress.XtraReports.UI.XRCrossBandBox Box3;
        private DevExpress.XtraReports.UI.XRCrossBandBox Box4;
        private DevExpress.XtraReports.UI.CalculatedField sum_nds;
        private DevExpress.XtraReports.UI.CalculatedField sum_end;
        private DevExpress.XtraReports.UI.CalculatedField full_rate;
        private DevExpress.XtraReports.Parameters.Parameter org_title;
        private DevExpress.XtraReports.Parameters.Parameter org_director;
        private DevExpress.XtraReports.Parameters.Parameter doc_number;
        private DevExpress.XtraReports.Parameters.Parameter agreement_note;
        private DevExpress.XtraReports.Parameters.Parameter string_sum;
        private DevExpress.XtraReports.Parameters.Parameter line_number;
    }
}
