//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectorWeb.Reports {
    
    public partial class Docs_Agreements : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "InspectorWeb.Reports.Docs_Agreements.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.Text2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text2");
            this.Text1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text1");
            this.Text3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text3");
            this.Text4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text4");
            this.Text5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text5");

            // Parameters
            this.doc_date = reportInitializer.GetParameter("doc_date");
            this.org_title = reportInitializer.GetParameter("org_title");
            this.org_director = reportInitializer.GetParameter("org_director");
            this.org_adress = reportInitializer.GetParameter("org_adress");
            this.doc_id = reportInitializer.GetParameter("doc_id");
            this.user_division = reportInitializer.GetParameter("user_division");
            this.org_region_number = reportInitializer.GetParameter("org_region_number");
            this.org_inn = reportInitializer.GetParameter("org_inn");
            this.org_kpp = reportInitializer.GetParameter("org_kpp");
            this.org_ca = reportInitializer.GetParameter("org_ca");
            this.org_sa = reportInitializer.GetParameter("org_sa");
            this.org_bank = reportInitializer.GetParameter("org_bank");
            this.org_payment_adressee = reportInitializer.GetParameter("org_payment_adressee");
            this.org_bank_bik = reportInitializer.GetParameter("org_bank_bik");
            this.bank = reportInitializer.GetParameter("bank");
            this.org_title_short = reportInitializer.GetParameter("org_title_short");
            this.doc_year = reportInitializer.GetParameter("doc_year");
            this.org_bank_saccount = reportInitializer.GetParameter("org_bank_saccount");
            this.org_director_short = reportInitializer.GetParameter("org_director_short");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.XRLabel Text2;
        private DevExpress.XtraReports.UI.XRLabel Text1;
        private DevExpress.XtraReports.UI.XRLabel Text3;
        private DevExpress.XtraReports.UI.XRLabel Text4;
        private DevExpress.XtraReports.UI.XRLabel Text5;
        private DevExpress.XtraReports.Parameters.Parameter doc_date;
        private DevExpress.XtraReports.Parameters.Parameter org_title;
        private DevExpress.XtraReports.Parameters.Parameter org_director;
        private DevExpress.XtraReports.Parameters.Parameter org_adress;
        private DevExpress.XtraReports.Parameters.Parameter doc_id;
        private DevExpress.XtraReports.Parameters.Parameter user_division;
        private DevExpress.XtraReports.Parameters.Parameter org_region_number;
        private DevExpress.XtraReports.Parameters.Parameter org_inn;
        private DevExpress.XtraReports.Parameters.Parameter org_kpp;
        private DevExpress.XtraReports.Parameters.Parameter org_ca;
        private DevExpress.XtraReports.Parameters.Parameter org_sa;
        private DevExpress.XtraReports.Parameters.Parameter org_bank;
        private DevExpress.XtraReports.Parameters.Parameter org_payment_adressee;
        private DevExpress.XtraReports.Parameters.Parameter org_bank_bik;
        private DevExpress.XtraReports.Parameters.Parameter bank;
        private DevExpress.XtraReports.Parameters.Parameter org_title_short;
        private DevExpress.XtraReports.Parameters.Parameter doc_year;
        private DevExpress.XtraReports.Parameters.Parameter org_bank_saccount;
        private DevExpress.XtraReports.Parameters.Parameter org_director_short;
    }
}
