//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectorWeb.Reports {
    
    public partial class Docs_Conclusion_Objects : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "InspectorWeb.Reports.Docs_Conclusion_Objects.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.Text25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text25");
            this.Text32 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text32");
            this.Text33 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text33");
            this.Text34 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text34");
            this.Text1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text1");
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");

            // Parameters
            this.doc_id = reportInitializer.GetParameter("doc_id");
            this.doc_date = reportInitializer.GetParameter("doc_date");
            this.specialist = reportInitializer.GetParameter("specialist");
            this.specialist1 = reportInitializer.GetParameter("specialist1");
            this.doc_num = reportInitializer.GetParameter("doc_num");
            this.org_title = reportInitializer.GetParameter("org_title");
            this.org_adress = reportInitializer.GetParameter("org_adress");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.XRLabel Text25;
        private DevExpress.XtraReports.UI.XRLabel Text32;
        private DevExpress.XtraReports.UI.XRLabel Text33;
        private DevExpress.XtraReports.UI.XRLabel Text34;
        private DevExpress.XtraReports.UI.XRLabel Text1;
        private DevExpress.XtraReports.Parameters.Parameter doc_id;
        private DevExpress.XtraReports.Parameters.Parameter doc_date;
        private DevExpress.XtraReports.Parameters.Parameter specialist;
        private DevExpress.XtraReports.Parameters.Parameter specialist1;
        private DevExpress.XtraReports.Parameters.Parameter doc_num;
        private DevExpress.XtraReports.Parameters.Parameter org_title;
        private DevExpress.XtraReports.Parameters.Parameter org_adress;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
    }
}
