//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectorWeb.Reports {
    
    public partial class Docs_Conclusion_Export_New : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "InspectorWeb.Reports.Docs_Conclusion_Export_New.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.Text25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text25");
            this.Text32 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text32");
            this.Text33 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text33");
            this.Text34 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text34");

            // Parameters
            this.doc_id = reportInitializer.GetParameter("doc_id");
            this.doc_date = reportInitializer.GetParameter("doc_date");
            this.specialist = reportInitializer.GetParameter("specialist");
            this.karantin_detected = reportInitializer.GetParameter("karantin_detected");
            this.notkarantin_detected = reportInitializer.GetParameter("notkarantin_detected");
            this.doc_num = reportInitializer.GetParameter("doc_num");
            this.org_title = reportInitializer.GetParameter("org_title");
            this.org_adress = reportInitializer.GetParameter("org_adress");
            this.good_titles = reportInitializer.GetParameter("good_titles");
            this.production_countries = reportInitializer.GetParameter("production_countries");
            this.places_weights = reportInitializer.GetParameter("places_weights");
            this.org_delegation_order = reportInitializer.GetParameter("org_delegation_order");

            // Calculated Fields
            this.kar_detected = reportInitializer.GetCalculatedField("kar_detected");
            this.notkar_detected = reportInitializer.GetCalculatedField("notkar_detected");
            this.is_act = reportInitializer.GetCalculatedField("is_act");
            this.is_transport = reportInitializer.GetCalculatedField("is_transport");
            this.is_wood_composition = reportInitializer.GetCalculatedField("is_wood_composition");
            this.is_remark = reportInitializer.GetCalculatedField("is_remark");
            this.is_bill = reportInitializer.GetCalculatedField("is_bill");
            this.is_origin = reportInitializer.GetCalculatedField("is_origin");
            this.origin_separator = reportInitializer.GetCalculatedField("origin_separator");
            this.is_mark = reportInitializer.GetCalculatedField("is_mark");
            this.is_fact_address = reportInitializer.GetCalculatedField("is_fact_address");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.XRLabel Text25;
        private DevExpress.XtraReports.UI.XRLabel Text32;
        private DevExpress.XtraReports.UI.XRLabel Text33;
        private DevExpress.XtraReports.UI.XRLabel Text34;
        private DevExpress.XtraReports.UI.CalculatedField kar_detected;
        private DevExpress.XtraReports.UI.CalculatedField notkar_detected;
        private DevExpress.XtraReports.UI.CalculatedField is_act;
        private DevExpress.XtraReports.UI.CalculatedField is_transport;
        private DevExpress.XtraReports.UI.CalculatedField is_wood_composition;
        private DevExpress.XtraReports.UI.CalculatedField is_remark;
        private DevExpress.XtraReports.UI.CalculatedField is_bill;
        private DevExpress.XtraReports.UI.CalculatedField is_origin;
        private DevExpress.XtraReports.UI.CalculatedField origin_separator;
        private DevExpress.XtraReports.UI.CalculatedField is_mark;
        private DevExpress.XtraReports.UI.CalculatedField is_fact_address;
        private DevExpress.XtraReports.Parameters.Parameter doc_id;
        private DevExpress.XtraReports.Parameters.Parameter doc_date;
        private DevExpress.XtraReports.Parameters.Parameter specialist;
        private DevExpress.XtraReports.Parameters.Parameter karantin_detected;
        private DevExpress.XtraReports.Parameters.Parameter notkarantin_detected;
        private DevExpress.XtraReports.Parameters.Parameter doc_num;
        private DevExpress.XtraReports.Parameters.Parameter org_title;
        private DevExpress.XtraReports.Parameters.Parameter org_adress;
        private DevExpress.XtraReports.Parameters.Parameter good_titles;
        private DevExpress.XtraReports.Parameters.Parameter production_countries;
        private DevExpress.XtraReports.Parameters.Parameter places_weights;
        private DevExpress.XtraReports.Parameters.Parameter org_delegation_order;
    }
}
