//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectorWeb.Reports {
    
    public partial class Docs_Act : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "InspectorWeb.Reports.Docs_Act.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.goodtitle1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("goodtitle1");
            this.productioncountry1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("productioncountry1");
            this.samplescount1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("samplescount1");
            this.weightunit1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("weightunit1");
            this.Line14 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line14");
            this.weight1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("weight1");
            this.Text1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text1");
            this.Text4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text4");
            this.Text6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text6");
            this.Line2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line2");
            this.Text7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text7");
            this.Text10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text10");
            this.Line3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line3");
            this.Text11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text11");
            this.Line4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line4");
            this.Text15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text15");
            this.Text19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text19");
            this.docdate1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("docdate1");
            this.Text12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text12");
            this.Text13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text13");
            this.Text3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text3");
            this.Text2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text2");
            this.Line19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line19");
            this.Text20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text20");
            this.Text21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text21");
            this.Line9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line9");
            this.Text22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text22");
            this.Line10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line10");
            this.Text23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text23");
            this.Text24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text24");
            this.Line11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line11");
            this.Line12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line12");
            this.Text25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text25");
            this.Text26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text26");
            this.specialist1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("specialist1");
            this.representative1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("representative1");
            this.Text5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text5");
            this.Line5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line5");
            this.Text8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text8");
            this.Line6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line6");
            this.Text9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text9");
            this.Box2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandBox>("Box2");
            this.Line15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line15");
            this.Line1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line1");
            this.Line17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line17");

            // Parameters
            this.doc_id = reportInitializer.GetParameter("doc_id");
            this.doc_date = reportInitializer.GetParameter("doc_date");
            this.specialist = reportInitializer.GetParameter("specialist");
            this.doc_num = reportInitializer.GetParameter("doc_num");
            this.org_title = reportInitializer.GetParameter("org_title");
            this.org_adress = reportInitializer.GetParameter("org_adress");
            this.org_telephone = reportInitializer.GetParameter("org_telephone");
            this.org_fax = reportInitializer.GetParameter("org_fax");

            // Calculated Fields
            this.fact_address_title = reportInitializer.GetCalculatedField("fact_address_title");
            this.fact_address = reportInitializer.GetCalculatedField("fact_address");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.XRLabel goodtitle1;
        private DevExpress.XtraReports.UI.XRLabel productioncountry1;
        private DevExpress.XtraReports.UI.XRLabel samplescount1;
        private DevExpress.XtraReports.UI.XRLabel weightunit1;
        private DevExpress.XtraReports.UI.XRLine Line14;
        private DevExpress.XtraReports.UI.XRLabel weight1;
        private DevExpress.XtraReports.UI.XRLabel Text1;
        private DevExpress.XtraReports.UI.XRLabel Text4;
        private DevExpress.XtraReports.UI.XRLabel Text6;
        private DevExpress.XtraReports.UI.XRLine Line2;
        private DevExpress.XtraReports.UI.XRLabel Text7;
        private DevExpress.XtraReports.UI.XRLabel Text10;
        private DevExpress.XtraReports.UI.XRLine Line3;
        private DevExpress.XtraReports.UI.XRLabel Text11;
        private DevExpress.XtraReports.UI.XRLine Line4;
        private DevExpress.XtraReports.UI.XRLabel Text15;
        private DevExpress.XtraReports.UI.XRLabel Text19;
        private DevExpress.XtraReports.UI.XRLabel docdate1;
        private DevExpress.XtraReports.UI.XRLabel Text12;
        private DevExpress.XtraReports.UI.XRLabel Text13;
        private DevExpress.XtraReports.UI.XRLabel Text3;
        private DevExpress.XtraReports.UI.XRLabel Text2;
        private DevExpress.XtraReports.UI.XRLine Line19;
        private DevExpress.XtraReports.UI.XRLabel Text20;
        private DevExpress.XtraReports.UI.XRLabel Text21;
        private DevExpress.XtraReports.UI.XRLine Line9;
        private DevExpress.XtraReports.UI.XRLabel Text22;
        private DevExpress.XtraReports.UI.XRLine Line10;
        private DevExpress.XtraReports.UI.XRLabel Text23;
        private DevExpress.XtraReports.UI.XRLabel Text24;
        private DevExpress.XtraReports.UI.XRLine Line11;
        private DevExpress.XtraReports.UI.XRLine Line12;
        private DevExpress.XtraReports.UI.XRLabel Text25;
        private DevExpress.XtraReports.UI.XRLabel Text26;
        private DevExpress.XtraReports.UI.XRLabel specialist1;
        private DevExpress.XtraReports.UI.XRLabel representative1;
        private DevExpress.XtraReports.UI.XRLabel Text5;
        private DevExpress.XtraReports.UI.XRLine Line5;
        private DevExpress.XtraReports.UI.XRLabel Text8;
        private DevExpress.XtraReports.UI.XRLine Line6;
        private DevExpress.XtraReports.UI.XRLabel Text9;
        private DevExpress.XtraReports.UI.XRCrossBandBox Box2;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line15;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line1;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line17;
        private DevExpress.XtraReports.UI.CalculatedField fact_address_title;
        private DevExpress.XtraReports.UI.CalculatedField fact_address;
        private DevExpress.XtraReports.Parameters.Parameter doc_id;
        private DevExpress.XtraReports.Parameters.Parameter doc_date;
        private DevExpress.XtraReports.Parameters.Parameter specialist;
        private DevExpress.XtraReports.Parameters.Parameter doc_num;
        private DevExpress.XtraReports.Parameters.Parameter org_title;
        private DevExpress.XtraReports.Parameters.Parameter org_adress;
        private DevExpress.XtraReports.Parameters.Parameter org_telephone;
        private DevExpress.XtraReports.Parameters.Parameter org_fax;
    }
}
