//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectorWeb.Reports {
    
    public partial class Docs_Bills_Pre : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "InspectorWeb.Reports.Docs_Bills_Pre.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.Line17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line17");
            this.unit1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("unit1");
            this.count1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("count1");
            this.RecordNumber1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("RecordNumber1");
            this.sum1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("sum1");
            this.Line1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line1");
            this.Text3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text3");
            this.fullrate1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("fullrate1");
            this.Text20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text20");
            this.Text22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text22");
            this.Text23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text23");
            this.Text24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text24");
            this.Text25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text25");
            this.Text26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text26");
            this.Text27 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text27");
            this.Text28 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text28");
            this.Text29 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text29");
            this.Text30 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text30");
            this.Text31 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text31");
            this.Text1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text1");
            this.Text2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text2");
            this.Text6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text6");
            this.Text7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text7");
            this.Text8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text8");
            this.Text11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text11");
            this.Text9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text9");
            this.Text10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text10");
            this.Text19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text19");
            this.Text12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text12");
            this.Line2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("Line2");
            this.Text4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text4");
            this.Text5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text5");
            this.nds1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("nds1");
            this.Text15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text15");
            this.Text16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text16");
            this.Text17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text17");
            this.sumwithoutnds1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("sumwithoutnds1");
            this.Text21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Text21");
            this.docsum1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("docsum1");
            this.Line11 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line11");
            this.Line12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line12");
            this.Line13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line13");
            this.Line16 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line16");
            this.Box2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandBox>("Box2");
            this.Line19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossBandLine>("Line19");

            // Parameters
            this.line_number = reportInitializer.GetParameter("line_number");
            this.sum_without_nds = reportInitializer.GetParameter("sum_without_nds");
            this.bill_number = reportInitializer.GetParameter("bill_number");
            this.doc_date = reportInitializer.GetParameter("doc_date");
            this.org_director = reportInitializer.GetParameter("org_director");
            this.org_buch = reportInitializer.GetParameter("org_buch");
            this.org_title = reportInitializer.GetParameter("org_title");
            this.org_adress = reportInitializer.GetParameter("org_adress");
            this.org_telephone = reportInitializer.GetParameter("org_telephone");
            this.org_account = reportInitializer.GetParameter("org_account");
            this.org_bank_bik = reportInitializer.GetParameter("org_bank_bik");
            this.org_bank_account = reportInitializer.GetParameter("org_bank_account");
            this.org_payment_target = reportInitializer.GetParameter("org_payment_target");
            this.org_bank = reportInitializer.GetParameter("org_bank");
            this.org_inn = reportInitializer.GetParameter("org_inn");
            this.org_kpp = reportInitializer.GetParameter("org_kpp");
            this.org_adressee = reportInitializer.GetParameter("org_adressee");
            this.string_sum = reportInitializer.GetParameter("string_sum");
            this.bank = reportInitializer.GetParameter("bank");
            this.org_kbk = reportInitializer.GetParameter("org_kbk");
            this.org_okato = reportInitializer.GetParameter("org_okato");

            // Calculated Fields
            this.nds = reportInitializer.GetCalculatedField("nds");
            this.full_rate = reportInitializer.GetCalculatedField("full_rate");
            this.isVans = reportInitializer.GetCalculatedField("isVans");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.XRLine Line17;
        private DevExpress.XtraReports.UI.XRLabel unit1;
        private DevExpress.XtraReports.UI.XRLabel count1;
        private DevExpress.XtraReports.UI.XRLabel RecordNumber1;
        private DevExpress.XtraReports.UI.XRLabel sum1;
        private DevExpress.XtraReports.UI.XRLine Line1;
        private DevExpress.XtraReports.UI.XRLabel Text3;
        private DevExpress.XtraReports.UI.XRLabel fullrate1;
        private DevExpress.XtraReports.UI.XRLabel Text20;
        private DevExpress.XtraReports.UI.XRLabel Text22;
        private DevExpress.XtraReports.UI.XRLabel Text23;
        private DevExpress.XtraReports.UI.XRLabel Text24;
        private DevExpress.XtraReports.UI.XRLabel Text25;
        private DevExpress.XtraReports.UI.XRLabel Text26;
        private DevExpress.XtraReports.UI.XRLabel Text27;
        private DevExpress.XtraReports.UI.XRLabel Text28;
        private DevExpress.XtraReports.UI.XRLabel Text29;
        private DevExpress.XtraReports.UI.XRLabel Text30;
        private DevExpress.XtraReports.UI.XRLabel Text31;
        private DevExpress.XtraReports.UI.XRLabel Text1;
        private DevExpress.XtraReports.UI.XRLabel Text2;
        private DevExpress.XtraReports.UI.XRLabel Text6;
        private DevExpress.XtraReports.UI.XRLabel Text7;
        private DevExpress.XtraReports.UI.XRLabel Text8;
        private DevExpress.XtraReports.UI.XRLabel Text11;
        private DevExpress.XtraReports.UI.XRLabel Text9;
        private DevExpress.XtraReports.UI.XRLabel Text10;
        private DevExpress.XtraReports.UI.XRLabel Text19;
        private DevExpress.XtraReports.UI.XRLabel Text12;
        private DevExpress.XtraReports.UI.XRLine Line2;
        private DevExpress.XtraReports.UI.XRLabel Text4;
        private DevExpress.XtraReports.UI.XRLabel Text5;
        private DevExpress.XtraReports.UI.XRLabel nds1;
        private DevExpress.XtraReports.UI.XRLabel Text15;
        private DevExpress.XtraReports.UI.XRLabel Text16;
        private DevExpress.XtraReports.UI.XRLabel Text17;
        private DevExpress.XtraReports.UI.XRLabel sumwithoutnds1;
        private DevExpress.XtraReports.UI.XRLabel Text21;
        private DevExpress.XtraReports.UI.XRLabel docsum1;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line11;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line12;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line13;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line16;
        private DevExpress.XtraReports.UI.XRCrossBandBox Box2;
        private DevExpress.XtraReports.UI.XRCrossBandLine Line19;
        private DevExpress.XtraReports.UI.CalculatedField nds;
        private DevExpress.XtraReports.UI.CalculatedField full_rate;
        private DevExpress.XtraReports.UI.CalculatedField isVans;
        private DevExpress.XtraReports.Parameters.Parameter line_number;
        private DevExpress.XtraReports.Parameters.Parameter sum_without_nds;
        private DevExpress.XtraReports.Parameters.Parameter bill_number;
        private DevExpress.XtraReports.Parameters.Parameter doc_date;
        private DevExpress.XtraReports.Parameters.Parameter org_director;
        private DevExpress.XtraReports.Parameters.Parameter org_buch;
        private DevExpress.XtraReports.Parameters.Parameter org_title;
        private DevExpress.XtraReports.Parameters.Parameter org_adress;
        private DevExpress.XtraReports.Parameters.Parameter org_telephone;
        private DevExpress.XtraReports.Parameters.Parameter org_account;
        private DevExpress.XtraReports.Parameters.Parameter org_bank_bik;
        private DevExpress.XtraReports.Parameters.Parameter org_bank_account;
        private DevExpress.XtraReports.Parameters.Parameter org_payment_target;
        private DevExpress.XtraReports.Parameters.Parameter org_bank;
        private DevExpress.XtraReports.Parameters.Parameter org_inn;
        private DevExpress.XtraReports.Parameters.Parameter org_kpp;
        private DevExpress.XtraReports.Parameters.Parameter org_adressee;
        private DevExpress.XtraReports.Parameters.Parameter string_sum;
        private DevExpress.XtraReports.Parameters.Parameter bank;
        private DevExpress.XtraReports.Parameters.Parameter org_kbk;
        private DevExpress.XtraReports.Parameters.Parameter org_okato;
    }
}
